version: '3.7'
services:
  nginx:
    image: hwarang/myweb:blue
    deploy:
      replicas: 2
      placement:
        constraints:
          - node.role==worker
      restart_policy:
        condition: on-failure
        max_attempts: 2
    environment:
      SERVICE_PORTS: 80
    ports:
      - "8001:80"